return {
	pde = {
		-- ai = false,
		angular = false,
		cpp = false,
		csharp = true,
		copilot = false,
		docker = true,
		elixir = false,
		flutter = false,
		go = false,
		html = true,
		java = false,
		json = true,
		julia = false,
		jupyter = false,
		kotlin = false,
		lua = true,
		python = true,
		r = false,
		react = true,
		ruby = false,
		rust = true,
		scala = false,
		solidity = false,
		svelte = true,
		tailwind = true,
		terraform = false,
		typescript = true,
		vuejs = true,
	},
}
